curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Bill/Dainty/bill@caldereng.com/Dick-tator
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Jim/Schaefer/toverune@gmail.com/Captain
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Adam/Fournier/afournierca@gmail.com/Wind%20Block
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Amie/Krasnozon/amiekrasnozon@gmail.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Chris/Wright/velotech1@gmail.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Dino/Bernno/dberno@priestly.ca/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Don/Coats/don@caledonhillscycling.com/Grandfather%20of%20cycling
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Hugh/Hill/hhill@sympatico.ca/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Jeff/Wheller/jdwheller@yahoo.ca/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Mark/Foullong/drfoullong@rogers.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Rod/Nicholle/rnicholle@rogers.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Sandy/Schaefer/toverune@gmail.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Scott/Beffort/sbeffort@rogers.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Scott/Dennison/scott@mgrp.com/Team%20Member
curl -k -i -X POST -H "Content-Type:application/json"  http://chr-data.cfapps.io/v1/newTeam/Sean/Bechtel/bechtel83@gmail.com/Coach"
